[entryPoints]
  [entryPoints.web]
    address = ":80"
  [entryPoints.websecure]
    address = ":443"

[providers]
  [providers.docker]
    endpoint = "unix:///var/run/docker.sock"
    exposedByDefault = false
    defaultRule = "Host(`{{ trimPrefix `/` .Name }}.localhost`)"

[api]
  dashboard = true

[ping]

[log]
  level = "DEBUG"